#!/usr/bin/env zsh

function wakenuc () {
  wakeonlan -i 192.168.3.255 -p 9 $1
}

function pingnuc () {
  ping -c 1 -t $1 > /dev/null 2>&1
}

# argument check
if [[ $# -eq 0 ]]; then
  echo "Don't know which Intel NUC to wake. Need index number. Exiting."
  exit 1
fi

# argument mapping
NUC_INDEX=$1

# get Intel NUC info (MAC and IP address) from /usr/local/etc/dhcpd.conf (if it exists)
if [[ -f /usr/local/etc/dhcpd.conf ]]; then
  NUC_INFO=$(egrep "^host nuc$NUC_INDEX" -A 2 /usr/local/etc/dhcpd.conf | tail -2)

  if [[ ! -z "$NUC_INFO" ]]; then
    NUC_MAC=$(echo $NUC_INFO | grep hardware | awk '{print $3}' | tr -d ';')
    NUC_IP=$(echo $NUC_INFO | grep fixed-address | awk '{print $2}' | tr -d ';')

    if [[ -z "$NUC_MAC" || -z "$NUC_IP" ]]; then
      echo "Can't determine MAC and/or IP address of Intel NUC nuc$NUC_INDEX. Aborting."
      exit 1
    else

      # ping the Intel NUC to see if it's online
      pingnuc $NUC_IP
      if [[ "$?" != 0 ]]; then

        # no ping response from the Intel NUC so we send a magic packet to wake it up
        wakenuc $NUC_MAC
        exit $?
      else
        echo "Intel NUC nuc$NUC_INDEX is already online. Exiting."
        exit 0
      fi
    fi
  else
    echo "Intel NUC nuc$NUC_INDEX not found in /usr/local/etc/dhcpd.conf. Aborting."
    exit 1
  fi
else
  echo "Required file /usr/local/etc/dhcpd.conf doesn't exist. Aborting."
  exit 1
fi
