---

# named provisioning block - configures libvirt storage
# run as 'root' via ansible's 'become' directive
# must be called with option '--ask-become-pass'
- name: configure disk-based storage
  block:
    - name: create directories for mount points
      file:
        path: '{{ data_lv_mount_point }}'
        mode: '0777'
        state: directory

    - name: create volume group {{ data_vg_name }}
      lvg:
        vg: '{{ data_vg_name }}'
        pvs: /dev/sda
        state: present

    - name: create logical volume {{ data_lv_name }} with size {{ data_lv_size }}
      lvol:
        vg: '{{ data_vg_name }}'
        lv: '{{ data_lv_name }}'
        size: '{{ data_lv_size }}'

    - name: derive lvm mapper device name from volume group {{ data_vg_name }}
      set_fact:
        data_vg_mapper: "{{ data_vg_name | regex_replace('-', '--') }}"

    - name: create filesystem on logical volume {{ data_lv_name }}
      filesystem:
        fstype: xfs
        dev: /dev/{{ data_vg_name }}/{{ data_lv_name }}

    - name: mount filesystem on logical volume {{ data_lv_name }}
      mount:
        path: '{{ data_lv_mount_point }}'
        src: /dev/mapper/{{ data_vg_mapper }}-{{ data_lv_name }}
        fstype: xfs
        opts: rw,relatime,attr2,inode64,noquota
        state: mounted

    - name: change mount point permissions
      file:
        path: '{{ data_lv_mount_point }}'
        mode: '0777'
        state: directory

    - name: create libvirt storage directory
      file:
        path: '{{ data_lv_mount_point }}/{{ libvirt_storage_directory }}/{{ libvirt_storage_pool }}'
        mode: '0777'
        state: directory
  become: yes

# named provisioning block - configures libvirt storage
- name: configure libvirt storage
  block:

    # handlers will always be triggered by setting the 'changed' condition
    # of the task to 'true'
    - name: define libvirt storage pool {{ libvirt_storage_pool }}
      virt_pool:
        command: define
        name: '{{ libvirt_storage_pool }}'
        xml: '{{ lookup("template", "{{ role_path }}/templates/storagepool.xml.j2") }}'
        state: present
      changed_when: true
      notify:
        - build libvirt storage pool
        - autostart libvirt storage pool

    - name: run libvirt storage pool handlers
      meta: flush_handlers
