---

# network device handling
- name: configure virbr88-dummy device
  include_tasks: restart_virbr88_dummy.yml

- name: configure virbr88 device
  include_tasks: restart_virbr88.yml

- name: reload systemd service definitions
  command:
    argv:
      - systemctl
      - daemon-reload
  become: yes

- name: load iptables rules
  command:
    argv:
      - iptables-restore
      - /etc/iptables/rules.v4.virbr88
  become: yes

- name: restart iptables service
  service:
    name: netfilter-persistent
    state: restarted
  become: yes

# libvirt handling
- name: start libvirtd
  service:
    name: libvirtd
    state: restarted
  become: yes

- name: enable libvirtd
  service:
    name: libvirtd
    enabled: yes
  become: yes

- name: start libvirt network
  virt_net:
    name: '{{ libvirt_network_name }}'
    state: active

- name: autostart libvirt network
  virt_net:
    autostart: yes
    name: '{{ libvirt_network_name }}'

- name: build libvirt storage pool
  virt_pool:
    command: build
    name: '{{ libvirt_storage_pool }}'
    state: active

- name: autostart libvirt storage pool
  virt_pool:
    autostart: yes
    name: '{{ libvirt_storage_pool }}'
