---
- hosts: nucs
  roles:
    - role: common
      tags: [ common ]
    - role: development
      tags: [ development ]
    - role: libvirt
      tags: [ libvirt ]
    - role: docker
      tags: [ docker ]
    - role: vagrant
      tags: [ vagrant ]
    - role: kubernetes
      tags: [ kubernetes ]
    - role: user
      tags: [ user ]
    - role: cleanup
      tags: [ cleanup ]
