---

- name: create libvirt network
  virt_net:
    command: create
    name: '{{ libvirt_network_name }}'
    state: active
  become: yes

- name: autostart libvirt network
  virt_net:
    autostart: yes
    name: '{{ libvirt_network_name }}'
  become: yes

- name: build libvirt storage pool
  virt_pool:
    command: build
    name: '{{ libvirt_storage_pool }}'
    state: active
  become: yes

- name: autostart libvirt storage pool
  virt_pool:
    autostart: yes
    name: '{{ libvirt_storage_pool }}'
  become: yes
